services:
  client:
    container_name: budgetproject-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    ports:
      # - '${PORT}:${PORT}'
      - '5174:5174'
    env_file:
      - ./client/.env
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    
  backend:
    container_name: budgetproject-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
