services:
  client:
    container_name: budgetproject-client
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      # - '${PORT}:${PORT}'
      - '5174:5174'
    env_file:
      - ./client/.env
    depends_on:
      - backend
    
  backend:
    container_name: budgetproject-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
